/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SkillSwitchSnapshot } from 'dsh-skill-switch/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$736b696c6c537769746368 {
    disableAll: () => Promise<RemoteResult<SkillSwitchSnapshot>>
    setEnabled: (name: string, enabled: boolean) => Promise<RemoteResult<SkillSwitchSnapshot>>
    setStorePath: (path: string) => Promise<RemoteResult<SkillSwitchSnapshot>>
    snapshot: () => Promise<RemoteResult<SkillSwitchSnapshot>>
  }
  interface TypertRemoteMap {
    'skillSwitch/disableAll': () => Promise<RemoteResult<SkillSwitchSnapshot>>
    'skillSwitch/setEnabled': (name: string, enabled: boolean) => Promise<RemoteResult<SkillSwitchSnapshot>>
    'skillSwitch/setStorePath': (path: string) => Promise<RemoteResult<SkillSwitchSnapshot>>
    'skillSwitch/snapshot': () => Promise<RemoteResult<SkillSwitchSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'skillSwitch': TypertRemoteNamespace$736b696c6c537769746368
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
