/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_skill_switch_skillSwitch_disableAll_result$schema = z.object({
  'platform': z.union([z.literal("supported"), z.literal("unsupported-platform")]).readonly(),
  'platformDiagnostic': z.string().readonly(),
  'storePath': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'managedEnabledCount': z.number().readonly(),
  'skills': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'sourcePath': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'status': z.union([z.literal("available"), z.literal("enabled"), z.literal("conflict"), z.literal("invalid"), z.literal("broken")]).readonly(),
  'managed': z.boolean().readonly(),
  'diagnostic': z.string().readonly(),
})).readonly(),
  'externalTargets': z.array(z.object({
  'name': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'kind': z.union([z.literal("directory"), z.literal("file"), z.literal("link"), z.literal("other")]).readonly(),
  'diagnostic': z.string().readonly(),
})).readonly(),
})
const dsh_skill_switch_skillSwitch_setEnabled_parameter_0$schema = z.string()
const dsh_skill_switch_skillSwitch_setEnabled_parameter_1$schema = z.boolean()
const dsh_skill_switch_skillSwitch_setEnabled_result$schema = z.object({
  'platform': z.union([z.literal("supported"), z.literal("unsupported-platform")]).readonly(),
  'platformDiagnostic': z.string().readonly(),
  'storePath': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'managedEnabledCount': z.number().readonly(),
  'skills': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'sourcePath': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'status': z.union([z.literal("available"), z.literal("enabled"), z.literal("conflict"), z.literal("invalid"), z.literal("broken")]).readonly(),
  'managed': z.boolean().readonly(),
  'diagnostic': z.string().readonly(),
})).readonly(),
  'externalTargets': z.array(z.object({
  'name': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'kind': z.union([z.literal("directory"), z.literal("file"), z.literal("link"), z.literal("other")]).readonly(),
  'diagnostic': z.string().readonly(),
})).readonly(),
})
const dsh_skill_switch_skillSwitch_setStorePath_parameter_0$schema = z.string()
const dsh_skill_switch_skillSwitch_setStorePath_result$schema = z.object({
  'platform': z.union([z.literal("supported"), z.literal("unsupported-platform")]).readonly(),
  'platformDiagnostic': z.string().readonly(),
  'storePath': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'managedEnabledCount': z.number().readonly(),
  'skills': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'sourcePath': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'status': z.union([z.literal("available"), z.literal("enabled"), z.literal("conflict"), z.literal("invalid"), z.literal("broken")]).readonly(),
  'managed': z.boolean().readonly(),
  'diagnostic': z.string().readonly(),
})).readonly(),
  'externalTargets': z.array(z.object({
  'name': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'kind': z.union([z.literal("directory"), z.literal("file"), z.literal("link"), z.literal("other")]).readonly(),
  'diagnostic': z.string().readonly(),
})).readonly(),
})
const dsh_skill_switch_skillSwitch_snapshot_result$schema = z.object({
  'platform': z.union([z.literal("supported"), z.literal("unsupported-platform")]).readonly(),
  'platformDiagnostic': z.string().readonly(),
  'storePath': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'managedEnabledCount': z.number().readonly(),
  'skills': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'sourcePath': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'status': z.union([z.literal("available"), z.literal("enabled"), z.literal("conflict"), z.literal("invalid"), z.literal("broken")]).readonly(),
  'managed': z.boolean().readonly(),
  'diagnostic': z.string().readonly(),
})).readonly(),
  'externalTargets': z.array(z.object({
  'name': z.string().readonly(),
  'targetPath': z.string().readonly(),
  'kind': z.union([z.literal("directory"), z.literal("file"), z.literal("link"), z.literal("other")]).readonly(),
  'diagnostic': z.string().readonly(),
})).readonly(),
})

export const TYPERT = {
  package: 'dsh-skill-switch',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-skill-switch#skillSwitch/disableAll',
      service: 'skillSwitch',
      namespace: 'skillSwitch',
      method: 'disableAll',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-skill-switch/types#SkillSwitchSnapshot',
        schema: dsh_skill_switch_skillSwitch_disableAll_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-skill-switch/src/index.ts","line":58,"column":3},
    },
    {
      id: 'dsh-skill-switch#skillSwitch/setEnabled',
      service: 'skillSwitch',
      namespace: 'skillSwitch',
      method: 'setEnabled',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'name',
          wire: 'name',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-skill-switch#skillSwitch/setEnabled:name',
            schema: dsh_skill_switch_skillSwitch_setEnabled_parameter_0$schema,
          },
        },
        {
          name: 'enabled',
          wire: 'enabled',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-skill-switch#skillSwitch/setEnabled:enabled',
            schema: dsh_skill_switch_skillSwitch_setEnabled_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-skill-switch/types#SkillSwitchSnapshot',
        schema: dsh_skill_switch_skillSwitch_setEnabled_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-skill-switch/src/index.ts","line":52,"column":3},
    },
    {
      id: 'dsh-skill-switch#skillSwitch/setStorePath',
      service: 'skillSwitch',
      namespace: 'skillSwitch',
      method: 'setStorePath',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-skill-switch#skillSwitch/setStorePath:path',
            schema: dsh_skill_switch_skillSwitch_setStorePath_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-skill-switch/types#SkillSwitchSnapshot',
        schema: dsh_skill_switch_skillSwitch_setStorePath_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-skill-switch/src/index.ts","line":64,"column":3},
    },
    {
      id: 'dsh-skill-switch#skillSwitch/snapshot',
      service: 'skillSwitch',
      namespace: 'skillSwitch',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-skill-switch/types#SkillSwitchSnapshot',
        schema: dsh_skill_switch_skillSwitch_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-skill-switch/src/index.ts","line":46,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
